steps:
  - id: 'authenticate-docker-cli'
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "$${DHI_IO_PASSWORD}" | docker login dhi.io --username $${DHI_IO_USERNAME} --password-stdin
        mkdir -p /workspace/.docker
        cp ~/.docker/config.json /workspace/.docker/config.json
    secretEnv: [ 'DHI_IO_USERNAME', 'DHI_IO_PASSWORD' ]
  - id: 'generate-backend-certs'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - |
        cat << EOF > dbpxy-server/src/main/resources/certs/key.pem
        $${GRPC_KEY_PEM}
        EOF
        cat << EOF > dbpxy-server/src/main/resources/certs/cert.pem
        $${GRPC_CERT_PEM}
        EOF
    secretEnv: [ 'GRPC_KEY_PEM', 'GRPC_CERT_PEM' ]
  - id: 'build-backend-using-maven'
    name: maven:3.9-amazoncorretto-25-debian
    entrypoint: mvn
    args: [ 'clean', 'install', 'spring-boot:build-image', '-q', '-Dmaven.test.skip=true', '-Drevision=${_VERSION}' ]
  - id: 'prepare-to-deploy-maven-artifacts'
    name: gcr.io/cloud-builders/mvn
    entrypoint: bash
    args:
      - '-c'
      - |
        mkdir -pv $${DBPXY_LIB_DIR}
        cp dbpxy-lib/target/dbpxy-lib-${_VERSION}.jar $${DBPXY_LIB_DIR}/dbpxy-lib-${_VERSION}.jar
        cp dbpxy-lib/target/dbpxy-lib-${_VERSION}-sources.jar $${DBPXY_LIB_DIR}/dbpxy-lib-${_VERSION}-sources.jar
        cp dbpxy-lib/.flattened-pom.xml $${DBPXY_LIB_DIR}/dbpxy-lib-${_VERSION}.pom
        md5sum dbpxy-lib/.flattened-pom.xml | awk '{print $1}' > $${DBPXY_LIB_DIR}/dbpxy-lib-${_VERSION}.pom.md5
        sha256sum dbpxy-lib/.flattened-pom.xml | awk '{print $1}' > $${DBPXY_LIB_DIR}/dbpxy-lib-${_VERSION}.pom.sha256
    env:
      - DBPXY_LIB_DIR=dbpxy-lib/target/gcp-deploy/com/dbpxy/dbpxy-lib/${_VERSION}
  - id: 'build-image-using-docker'
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build --tag dbpxy:${_VERSION} --build-arg VERSION=${_VERSION} --file dbpxy-server/Dockerfile dbpxy-server
        docker tag dbpxy:${_VERSION} ${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_DOCKER_REPOSITORY}/dbpxy:${_VERSION}
    env:
      - DOCKER_BUILDKIT=1
artifacts:
  mavenArtifacts:
    - repository: https://${_GCP_REGION}-maven.pkg.dev/${_GCP_PROJECT_ID}/${_MAVEN_REPOSITORY}
      deployFolder: dbpxy-lib/target/gcp-deploy
      groupId: com.dbpxy
      artifactId: dbpxy-lib
      version: ${_VERSION}
images:
  - ${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_DOCKER_REPOSITORY}/dbpxy:${_VERSION}
availableSecrets:
  secretManager:
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/GRPC_KEY_PEM/versions/1
      env: GRPC_KEY_PEM
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/GRPC_CERT_PEM/versions/1
      env: GRPC_CERT_PEM
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/DHI_IO_USERNAME/versions/1
      env: DHI_IO_USERNAME
    - versionName: projects/${_GCP_PROJECT_ID}/secrets/DHI_IO_PASSWORD/versions/1
      env: DHI_IO_PASSWORD
serviceAccount: projects/${_GCP_PROJECT_ID}/serviceAccounts/${_GCP_SVC_ACCOUNT}
options:
  logging: CLOUD_LOGGING_ONLY
