app:
  node: ${_pod_name:${HOSTNAME}}
  grpc:
    port: ${GRPC_PORT}
  google:
    spanner:
      project: ${GOOGLE_PROJECT:}
      instance: ${SPANNER_INSTANCE:}
      postgresql:
        database: ${POSTGRESQL_DATABASE}
        hostname: ${POSTGRESQL_HOSTNAME}
        port: ${POSTGRESQL_PORT}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
        url: jdbc:postgresql://${app.google.spanner.postgresql.hostname}:${app.google.spanner.postgresql.port}/${app.google.spanner.postgresql.database}?user=${app.google.spanner.postgresql.username}&password=${app.google.spanner.postgresql.password}
        show-sql: true

server:
  port: ${PORT}
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: ${APP_CONTEXT}

spring:
  main:
    banner-mode: off
  profiles:
    group:
      integration: integration
      qa: qa
      pr: pr

management:
  server:
    port: ${MGMT_PORT}
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  endpoints:
    enabled-by-default: false
    web:
      base-path: /manage
      exposure:
        include:
          - health

logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(tx=%X{transaction.id},query=%X{query.id} :) %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}'
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    dev.frndpovoa.project1: ${APP_LOG_LEVEL:INFO}
